### ISSUE TITLE
Osori 내부 프로젝트 컨트리뷰트하기

### ISSUE THREAD

**Issue by JunsuLime** [HyOsori/Osori-Android#20]
진행하고 싶은 프로젝트를 댓글로 남겨주세요!

**Comment by JunsuLime** [comment]
### 내부 컨트리뷰트
[Osori HackDay](https://github.com/HyOsori/Osori-HackDay)

### 외부 컨트리뷰트
[생각중 ...](https://github.com/settings/profile)

**Comment by kimjieun02** [comment]
### 내부 컨트리뷰트
[Osori HackDay](https://github.com/HyOsori/Osori-HackDay)

### 외부 컨트리뷰트
생각중22

**Comment by Wanjuuuuu** [comment]
### 내부 컨트리뷰트
[Osori KareltheRobot](https://github.com/HyOsori/KareltheRobot)

### 외부 컨트리뷰트
생각중33

**Comment by clucle** [comment]
내부
hyson-csharp, algorithm, equalizer중에 생각중
외부
44
