### ISSUE TITLE
다음주 까지 해야할 일 (5.21까지)

### ISSUE THREAD

**Issue by JunsuLime** [HyOsori/Osori-Android#23]
* example 파일 참고 혹은 알아서 맡은 레포지토리 `README.md`, `CONTRIBUTING.md` 작성하기
* 각자 맡은 레포지토리 branch 관리하기 (master, develop, feature)
* 각자의 레포지토리를 위해 한 일 댓글로 적기!!

**Comment by JunsuLime** [comment]
예시)
https://github.com/HyOsori/HackDay

운영체제 과제도 열심히 하고 알고리즘도 열심히 하며 밥도 잘 먹고 살고 있습니다.

**Comment by JunsuLime** [comment]
Contribute 할 내부 repository 가 HyOsori 에 많이 없다는 문제가 있더군요.

1) 혹시 할 만한 내용이 있다면, 내부 repository 에 contribute 해주시고

2) 그렇지 않다면, 저희가 Contribute 하기 위해 도움이 될만한 내용을 댓글로 달아주세요

둘 중 하나는 꼭 해주세요!!

**Comment by Wanjuuuuu** [comment]
https://opentutorials.org/module/544/4998

죽지 못해 살고 있어요... 주르륵
위의 링크를 다시 공부해보면서 pyQt로 어떤 구성으로 editor를 만들지에 대해서 고민하고 있습니다.
다음주까지 CONTRIBUTING.md 를 작성할 예정입니다.........
모두 행복하세여~ㅎㅎ

**Comment by JunsuLime** [comment]
https://github.com/HyOsori/HackDay

1) Tornado + Angular migrated 된 개발 환경 구축완료
2) CONTRIBUTING.md 파일 PULL REQUEST 대기 중

**Comment by kimjieun02** [comment]
https://github.com/HyOsori/HackDay

1. README.md 파일 PULL REQUEST 대기 중
2. component tree 구상중 <- 화요일에 이야기했으면 합니당
3. 개발 환경 테스트 <- 이것도 이야기할 부분이 생겼습니다

저는 부산에서 잘 쉬다가 오늘 낮에 다시 서울로 올라갈 예정입니다.
다들 즐거운 주말이셨길 바라고 화요일에 뵙겠습니다!
