### ISSUE TITLE
Contributor 에게 하고싶은 질문을 써주세요

### ISSUE THREAD

**Issue by clucle** [HyOsori/Osori-Android#28]
훗

**Comment by kimjieun02** [comment]
@clucle 미리 작성해두신 질문도 여기 공유해주실 수 있을까요?

**Comment by clucle** [comment]
1. 컨트리뷰트를 하게 된 계기 (평소에 사용, 컨트리뷰트를 하기 위해서)
2. 주로 어떤 이슈들을 해결하는지
3. 이슈를 분석하고 컨트리뷰트에 쏟는 노력은 어느 정도일까? (시간)
4. 처음 컨트리뷰트할 때 부담이 될텐데 어떻게 시작 할 수 있었는지

**Comment by kimjieun02** [comment]
owner와 소통할 때 어느 정도 수준의 영어 실력이 필요한지?

**Comment by clucle** [comment]
최종 질문 목록

1. 컨트리뷰트를 하게 된 계기가 뭔가요? (평소에 사용, 컨트리뷰트를 하기 위해서)
2. 처음 시작할 때 배워서 하셨나요? 아니면 공부하셔서 하셨나요?
3. 주로 어떤 이슈들을 찾아서 컨트리뷰트 하시나요?
4. 이슈를 분석하고 컨트리뷰트에 쏟는 노력은 어느 정도일까요? (시간이나 등등)
5. 처음 컨트리뷰트할 때 부담이 될 텐데 어떻게 시작 할 수 있었는지 궁금해요
6. owner와 대화에 필요한 영어의 정도는 어느정도일까요?
