### ISSUE TITLE
Make wiki section for android study

### ISSUE THREAD

**Issue by JunsuLime** [HyOsori/Osori-Android#7]
## 주제

1) context 란?

2) AsyncTask 란? 그리고 여러가지 AsyncTask 구현 방법

3) RecyclerView 에 대하여 ...

4) 로그인  창 만들기 (EditText는 가운데 보다 밑으로 가게 만들기) - 화면만 만들기

5) to be continue

.. 이외에도 계속 이어서 진행할 예정

**Comment by clucle** [comment]
Add 2
Difference of AsyncTask, RxAndroid

**Comment by JunsuLime** [comment]
매주 android study 한 내용을 wiki 에 link 걸어 올리는 것으로 대체
